# Generated by Django 6.0 on 2026-01-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Optional display name (defaults to username)', max_length=20),
        ),
    ]
