# Generated by Django 6.0 on 2026-01-03
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0004_category_model_and_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_pid",
            field=models.CharField(
                blank=True,
                help_text="Store Stripe payment intent id for auditing.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                help_text="Store Stripe checkout session id for tracing.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunSQL(
            sql="UPDATE orders_order SET status='paid' WHERE status='completed';",
            reverse_sql="UPDATE orders_order SET status='completed' WHERE status='paid';",
        ),
        migrations.CreateModel(
            name="AccessEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entitlements",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-granted_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="accessentitlement",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_entitlement_per_user_product"
            ),
        ),
    ]
