# Generated by Django 6.0 on 2026-01-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_stripe_fields_accessentitlement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="stripe_pid",
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe payment intent ID for auditing",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe checkout session ID for tracing",
                max_length=255,
            ),
        ),
    ]
