# Generated by Django 6.0 on 2026-01-13 12:58

from django.db import migrations


def normalize_order_statuses(apps, schema_editor):
    """Normalize legacy order statuses to the current canonical values."""
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(status="completed").update(status="paid")


def noop_reverse(apps, schema_editor):
    """Do nothing on reverse to avoid data corruption."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_stripe_pid_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_order_statuses, reverse_code=noop_reverse),
    ]
