# Generated by Django 6.0 on 2026-01-15 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_safe_status_normalization'),
        ('products', '0009_alter_product_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessentitlement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='products.product'),
        ),
    ]
