# Generated by Django 6.0 on 2026-01-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_alt",
            field=models.CharField(
                default="Decorative archive entry image used as a visual preview",
                help_text="Describe the image for accessibility and SEO",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
