# Generated by Django 6.0 on 2026-01-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_image_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Archive category (e.g., Lore, Rituals, Chronicles)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Full archive text, visible only after purchase",
            ),
        ),
    ]
