# Generated by Django 6.0 on 2026-01-05 13:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_category_model_and_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                default="",
                help_text="Full archive text, visible only after purchase",
            ),
        ),
    ]
