# Generated by Django 6.0 on 2026-01-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_deal",
            field=models.BooleanField(default=False),
        ),
    ]
