# Generated by Django 6.0 on 2026-01-09 11:05

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_is_deal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Full content (visible after purchase)",
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(help_text="Public teaser description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_alt",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_deal",
            field=models.BooleanField(
                default=False, help_text="Mark as deal to show in archive deals filter"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="tagline",
            field=models.CharField(help_text="Short preview text", max_length=250),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="DealBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main text to display (e.g., 'DEAL', 'HOT', 'NEW')",
                        max_length=100,
                    ),
                ),
                (
                    "message",
                    models.CharField(help_text="Banner message text", max_length=200),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Optional: Custom URL (used if no product is linked)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="💰",
                        help_text="Emoji icon (e.g., 💰, 🔥, ⭐, 🎁)",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower = first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Show category badge",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link to a specific product",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal Banner",
                "verbose_name_plural": "Deal Banners",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
