# Generated by Django 6.0 on 2026-01-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_category_options_alter_category_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deal_exclude",
            field=models.BooleanField(
                default=False,
                help_text="This flag excludes a product from category deal banners",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="deal_manual",
            field=models.BooleanField(
                default=False, help_text="This flag forces a product to be a deal"
            ),
        ),
        migrations.AlterField(
            model_name="dealbanner",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Show category badge and filter by category when clicked",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="dealbanner",
            name="icon",
            field=models.CharField(
                default="💰",
                help_text="Emoji icon (e.g. 💰, 🔥, ⭐, 🎁)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dealbanner",
            name="title",
            field=models.CharField(
                help_text="Main text to display (e.g. 'DEAL', 'HOT', 'NEW')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_deal",
            field=models.BooleanField(
                default=False, help_text="Deal status used by filters and UI"
            ),
        ),
    ]
