# Generated by Django 6.0 on 2026-01-15 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_deal_exclude_product_deal_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Recommended 60-125 chars. Max 150.', max_length=255, validators=[django.core.validators.MaxLengthValidator(150)]),
        ),
    ]
