# Generated by Django 6.0 on 2026-01-20 12:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealbanner',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage (0-100). Applied to linked product or category products.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
