# Generated by Django 6.0 on 2026-01-21 16:27

import django.core.validators
import django_ckeditor_5.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_dealbanner_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deal_exclude',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deal_manual',
        ),
        migrations.AlterField(
            model_name='dealbanner',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage 0-100. Applied to linked product or category products.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dealbanner',
            name='icon',
            field=models.CharField(default='💰', help_text='Emoji icon (e.g. 💰, 🔥, ⚡, ✨)', max_length=10),
        ),
        migrations.AlterField(
            model_name='dealbanner',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower first)'),
        ),
        migrations.AlterField(
            model_name='dealbanner',
            name='title',
            field=models.CharField(help_text='Main text to display (e.g. DEAL, HOT, NEW)', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Full content visible after purchase', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deal',
            field=models.BooleanField(default=False, help_text='Deal status (used by filters and UI)'),
        ),
    ]
