# Generated by Django 6.0 on 2026-01-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_deal_exclude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealbanner',
            options={'ordering': ['-is_featured', 'order', '-created_at'], 'verbose_name': 'Deal Banner', 'verbose_name_plural': 'Deal Banners'},
        ),
        migrations.AddField(
            model_name='dealbanner',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured banners appear first in the carousel'),
        ),
    ]
