# Generated by Django 6.0 on 2026-01-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_dealbanner_options_dealbanner_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealbanner',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='Featured banners appear first in the carousel'),
        ),
    ]
