# Generated by Django 6.0 on 2026-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_dealbanner_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_removed',
            field=models.BooleanField(
                default=False,
                help_text='Removed from the public site but retained for entitled users.',
            ),
        ),
    ]
